/* Player-safe Marr setting data. No referee-only material is stored in this file. */
(() => {
if (window.MARR_ATLAS) return;
const S = (name, line, ...traits) => ({ name, line, traits });
const E = (id, name, type, x, y, description, facts, stat, wares = []) => ({
  id,
  name,
  type,
  x,
  y,
  description,
  facts,
  stat,
  wares,
});

const MARR_DESTINATIONS = [
  {
    id: "tree",
    marker: 1,
    name: "Tree of Marr",
    short: "The city’s living heart",
    subtitle: "Five bough-halls above; five root-halls below",
    icon: "♧",
    x: 50,
    y: 27,
    image: "/maps/tree-of-marr.webp",
    alt: "Charcoal cross-section map of the Tree of Marr",
    description:
      "Older than the wall and broader than a keep, the Tree shelters homes, halls, cages, and root-chambers. Its bark is scarred with generations of names. Citizens touch the trunk before difficult promises.",
    facts: [
      "Public lifts and spiral stairs connect Upper I–V during daylight.",
      "Lower halls are cool, damp, and regulated by bell-signs painted on the walls.",
      "Cage platforms are visible from the bough walks; do not throw food or tools upward.",
    ],
    entries: [
      E(
        "upper-1",
        "Upper I — Crown Walk",
        "Bough terrace",
        20,
        17,
        "An open platform among the highest leaves. Wind bells announce changing weather, and citizens tie ribbons for the absent.",
        ["A careful circuit takes one exploration turn.", "High winds require a DEX save when carrying a bulky item."],
        S("Crown Wind", "Site • DEX save • fall: d8 STR", "Ropes or a guide make the save unnecessary.", "A dropped item lands on Upper II on a favorable Die of Fate.")
      ),
      E(
        "upper-2",
        "Upper II — Lantern Gallery",
        "Public hall",
        17,
        29,
        "A broad gallery of hanging lanterns, civic notices, and long benches. Guides wait beneath the green-glass lamp.",
        ["Lantern guide: 5 gp per day.", "A hot meal and bench-rest cost 3 gp."],
        S("Pella Wick, Lantern Guide", "4 HP, 10 STR, 13 DEX, 12 WIL, staff (d6)", "Knows the public lifts, street signs, and safe daylight routes.", "Never leaves a traveler behind once paid.")
      ),
      E(
        "upper-3",
        "Upper III — Assembly Ring",
        "Civic chamber",
        18,
        41,
        "A circular room of worn stools where petitions are heard aloud. Any citizen may stand at the center stone and ask to be entered in the day-book.",
        ["Speaking time is limited to one sandglass.", "WIL save to keep composure before a hostile crowd."],
        S("Assembly Crowd", "6 HP, 10 STR, 10 DEX, 13 WIL, thrown debris (d6 blast), detachment", "Calms if offered a fair hearing.", "Critical Damage: the speaker is driven from the ring and cannot petition again that day.")
      ),
      E(
        "upper-4",
        "Upper IV — Orrery Hall",
        "Study hall",
        19,
        53,
        "A rootwood orrery turns by waterweight. Its brass moons are polished by apprentices, and its public chart predicts tides and festivals.",
        ["A scholar may answer one astronomical question for 20 gp per day.", "Touching the moving rings calls for a DEX save or d4 STR damage."],
        S("Rootwood Orrery", "Device • DEX save • gears: d4 STR", "Stopping it makes all attacks against the mechanism enhanced.", "Resetting it takes an hour and specialized tools.")
      ),
      E(
        "upper-5",
        "Upper V — Petition Hall",
        "Threshold hall",
        20,
        65,
        "Four root-arched corridors meet beneath a dome of dark wood. Queue cords separate citizens, traders, and official messengers.",
        ["Public business is heard from dawn until the second bell.", "Weapons must remain bound or peace-tied."],
        S("Tree Usher", "5 HP, 1 Armor, 12 STR, 11 DEX, 13 WIL, cudgel (d6)", "Uses names and procedure before force.", "Will summon a four-person watch detachment if violence begins.")
      ),
      E(
        "lower-1",
        "Lower I — Chain House",
        "Root chamber",
        82,
        17,
        "A square chamber where lift chains are inspected, oiled, and counted. The air tastes of iron and wet bark.",
        ["Crossing beneath an active lift requires a DEX save.", "Chain, 10 ft: 10 gp when surplus is posted."],
        S("Lift Chain", "Hazard • DEX save • crush: d10 STR", "A clear bell rings one round before movement.", "A jammed chain can be braced with STR 14 effort and proper leverage.")
      ),
      E(
        "lower-2",
        "Lower II — Cask Cells",
        "Store rooms",
        82,
        30,
        "Round root-cells hold water, lamp oil, pickles, and public grain. Each door bears a tally slate.",
        ["Rations (3 uses): 10 gp.", "Oil can (6 uses): 10 gp."],
        S("Storehouse Tender", "3 HP, 9 STR, 10 DEX, 12 WIL, key-ring (d4)", "Will trade fairly against posted civic prices.", "Carries a whistle audible through the lower halls.")
      ),
      E(
        "lower-3",
        "Lower III — Whispering Ways",
        "Root passage",
        82,
        42,
        "Narrow loops where root hollows repeat the last sentence spoken. Travelers use chalk marks and knotted twine.",
        ["A loud statement returns one turn later.", "Without a guide, save WIL to avoid following a familiar echo."],
        S("Borrowed Echo", "3 HP, 6 STR, 14 DEX, 14 WIL, remembered voice (d6 WIL)", "Cannot be harmed by mundane weapons; direct sunlight disperses it.", "Critical Damage: target adds 1 Fatigue from sleepless repetition.")
      ),
      E(
        "lower-4",
        "Lower IV — Root Scriptorium",
        "Archive hall",
        82,
        55,
        "Readers copy public genealogies and civic songs beneath shaded lamps. Ink dries slowly in the humid air.",
        ["Reading access is free; a copyist costs 20 gp per day.", "Parchment (3 uses): 10 gp."],
        S("Senior Copyist Ambrin", "3 HP, 8 STR, 10 DEX, 15 WIL, ink knife (d4)", "Can identify public seals and common scripts.", "Refuses payment to falsify a living person’s name.")
      ),
      E(
        "lower-5",
        "Lower V — Memory Rotunda",
        "Public memorial",
        82,
        67,
        "A circular walk around a pale root column. Names spoken here carry gently through the room, even at a whisper.",
        ["A full turn of quiet rest restores HP.", "A character who speaks a sincere remembrance clears 1 Fatigue once per week."],
        S("Memory Rotunda", "Sanctuary • WIL save • no damage", "Violence here immediately deprives the aggressor until they make amends.", "Spoken names linger until sunrise.")
      ),
      E(
        "watch-door",
        "Daemos Watch Door",
        "Fortified threshold",
        33,
        43,
        "A stone-faced gatehouse grown into the western trunk. Entry is controlled by posted civic rules and a pair of iron shutters.",
        ["Visitors surrender open flame at the desk.", "A visitor token grants access to the public hall only."],
        S("Watch Door Detail", "6 HP, 2 Armor, 12 STR, 11 DEX, 13 WIL, polearms (d10), detachment", "Challenges unknown armed groups before attacking.", "Morale uses the desk sergeant’s 14 WIL.")
      ),
      E(
        "book",
        "The Book of Souls",
        "Publicly revered relic",
        50,
        70,
        "A colossal open volume seated among the oldest roots. Pilgrims view it from behind a low stone rail while readers maintain a continuous vigil.",
        ["The public may offer a written name at the rail.", "Touching the leaves is forbidden and physically difficult."],
        S("The Great Book", "Relic • 24 HP, 3 Armor, 18 STR, 3 DEX, 18 WIL", "Mundane attacks are impaired; fire is extinguished within near distance.", "A reader who forces contact saves WIL or adds 1 Fatigue from overwhelming voices.")
      ),
      E(
        "depths",
        "The Continuing Depths",
        "Root frontier",
        52,
        88,
        "Below the last public stair, the roots descend beyond maintained lamps. A brass sign names required provisions and records the day’s closures.",
        ["Lantern, rope, rations, and a named return contact are required.", "Unlit travel makes all navigation saves impaired."],
        S("Deep-Root Exposure", "Journey • WIL save each watch • failure: 1 Fatigue", "A local guide removes the first save each day.", "Rest is unsafe unless the party establishes light, water, and a defensible camp.")
      ),
    ],
  },
  {
    id: "cages",
    marker: 2,
    name: "Prison Cages",
    short: "Iron lanterns among the limbs",
    subtitle: "Visible justice, cold wind, and hard bargains",
    icon: "⌗",
    x: 51,
    y: 32,
    image: "/maps/prison-cages.webp",
    alt: "Focused charcoal map of the prison cages in the Tree of Marr",
    description:
      "Iron cages hang at measured distances from the Tree’s great limbs. Their numbers are visible from the square. A public desk records names, sentences, meal deliveries, and petitions.",
    facts: [
      "Visitors may speak from the marked platform during the noon bell.",
      "Food parcels are searched but accepted when properly wrapped.",
      "Tampering with chains closes the platform for everyone.",
    ],
    entries: [
      E("cage-desk", "Petition Desk", "Public office", 18, 78, "A narrow counter beneath a rain awning. Clerks record visits and accept signed petitions.", ["Petition copy: 1 gp.", "WIL save only when attempting an extraordinary exception."], S("Cage Clerk", "3 HP, 8 STR, 10 DEX, 13 WIL, ruler (d4)", "Knows posted sentences and visiting hours.", "Calls guards rather than fighting.")),
      E("visitor-platform", "Visitor Platform", "Bough platform", 45, 60, "A railed stand facing the lower cages. Voices carry poorly through wind and leaves.", ["One visitor may speak at a time.", "Save WIL to communicate a delicate message in ten words."], S("Crosswind", "Site • WIL save • failure: message is incomplete", "A speaking trumpet grants advantage in the fiction.", "No damage unless someone climbs the rail.")),
      E("lower-cages", "Lower Cages", "Hanging cells", 82, 72, "The nearest cages sway above the square. Each has a water cup, a blanket, and a wooden sentence plaque.", ["A caged person has room to sit but not pace.", "Reaching a cage from the limb requires a DEX save."], S("Hanging Cage", "12 HP, 2 Armor, 16 STR, 6 DEX, 12 WIL, swinging bars (d6)", "Bulky iron; immune to ordinary cutting tools.", "Critical Damage: a support pin bends and the cage drops one level.")),
      E("chain-walk", "Chain Walk", "Maintenance route", 80, 22, "A narrow service bridge follows the anchor chains. Only licensed tenders may cross it.", ["Spiked boots: 15 gp.", "Crossing in rain requires a DEX save or d6 STR damage from a fall to the catch net."], S("Chain Tender", "5 HP, 1 Armor, 12 STR, 13 DEX, 11 WIL, hook-pole (d8)", "Secures people before cargo.", "Will cut loose a failing empty cage to save the main limb.")),
      E("parcel-table", "Parcel Table", "Service stall", 65, 43, "Meals, letters, and blankets are wrapped here under public inspection.", ["Plain cage bread: 1 gp.", "Writing kit and witnessed letter: 5 gp."], S("Parcel Search", "Procedure • DEX or WIL save when concealing an item", "Failure means the parcel is refused and recorded.", "Honest parcels pass without a roll.")),
    ],
  },
  {
    id: "village",
    marker: 3,
    name: "Marr Village",
    short: "Roofs in the western shade",
    subtitle: "Homes, inns, crafts, and the ordinary courage of living",
    icon: "⌂",
    x: 27,
    y: 41,
    image: "/maps/marr-village.webp",
    alt: "Focused charcoal map of Marr Village",
    description:
      "Timber houses crowd the western arc between wall and root. Doors remain open during daylight, and every lane seems to possess its own kettle, bench, and rumor.",
    facts: ["Most shops close at the evening bell.", "Public water barrels stand at every third lane.", "A blue cord above a door means travelers may ask for shelter."],
    entries: [
      E("bent-lantern", "The Bent Lantern", "Inn", 49, 25, "A low-beamed inn known for thick stew and quiet tables.", ["Room and board: 10 gp.", "Private room for four: 35 gp."], S("Mara Fen, Innkeeper", "4 HP, 11 STR, 10 DEX, 14 WIL, ladle (d6)", "Remembers faces and unpaid tabs.", "Offers water and a bench before asking questions.")),
      E("cordwainer", "Nine-Peg Cordwainer", "Workshop", 72, 31, "Boots, straps, harness, and careful repairs hang from nine pegs.", ["Repair one worn item: 5 gp.", "Spiked boots: 15 gp."], S("Old Rusk", "3 HP, 9 STR, 12 DEX, 12 WIL, awl (d4)", "Can judge a traveler’s last road from their soles.", "Will not rush work that bears a person’s weight.")),
      E("wash-house", "Steamroot Wash-House", "Bath house", 39, 58, "Root-warmed water fills stone tubs behind woven screens.", ["Bathing goods: 5 gp.", "A full wash and laundry clears ordinary grime in one turn."], S("Boiler Steam", "Hazard • DEX save • scald: d4 STR", "Warning pipes knock before pressure releases.", "Closing the red valve ends the hazard.")),
      E("candle-house", "Three Wicks", "Chandler", 68, 62, "Beeswax, tallow, lamp cups, and smoky glass are sold by weight.", ["Torch (3 uses): 5 gp.", "Lantern: 10 gp; oil (6 uses): 10 gp."], S("Iven Three-Wicks", "3 HP, 8 STR, 11 DEX, 13 WIL, hot wax (d4)", "Tests every wick before sale.", "Open flame near the tallow makes attacks blast on a failed Die of Fate.")),
      E("common-oven", "Common Oven", "Neighborhood hearth", 50, 81, "Families mark dough with carved stamps and bake in the shared brick oven.", ["One stamped loaf: 1 gp.", "Rations (3 uses): 10 gp."], S("Oven Fire", "Site • DEX save • burn: d6 STR", "Long tools avoid the save.", "Quenching the oven ruins every loaf and makes the lane hostile.")),
      E("wall-stairs", "West Wall Stairs", "Public route", 14, 64, "Broad steps climb to the parapet gardens and watch path.", ["The parapet offers a clear view beyond Marr.", "A patrol passes each watch."], S("Village Watch Pair", "4 HP, 1 Armor, 12 STR, 11 DEX, 12 WIL, spears (d8)", "Helpful toward lost travelers; firm about closed gates.", "One carries a horn that summons a detachment in two rounds.")),
    ],
  },
  {
    id: "green",
    marker: 4,
    name: "Village Green",
    short: "Marr’s field of games",
    subtitle: "Three old sports, one broad commons",
    icon: "◉",
    x: 36,
    y: 59,
    image: "/maps/village-green.webp",
    alt: "Focused charcoal map of Marr Village Green",
    description:
      "A circular green in the western shade. Chalk arcs, turf scars, stone rings, and crown-posts show that Marr built its commons around games rather than ceremony.",
    facts: ["Casual play is free when no league match is posted.", "Borrowed gear requires a name-token.", "Spectators stand outside the white root-line."],
    entries: [
      E("roughball", "Roughball Pitch", "Team sport", 28, 37, "Two teams of five carry, kick, or bat a stitched root-leather ball through the rival fork-goal. A carrier may take only three strides before passing.", ["First to 5 goals wins.", "No metal equipment; holds end when a knee touches turf.", "A foul grants an unopposed throw from the nearest chalk arc."], S("Cairn Match", "Three exchanges • STR, DEX, then WIL saves", "Each success scores 1 Edge; best total wins the exchange.", "On a failed save, choose: lose the ball or take d4 STR damage. Armor does not apply.")),
      E("girdle-ring", "The Girdle Ring", "Grappling sport", 78, 42, "Two wrestlers grip a common leather girdle. Win by forcing both of the opponent’s feet outside the ring or making their shoulder touch turf.", ["Best two falls of three.", "Grips stay on the girdle; no striking or joint locks.", "Breaking grip yields the fall."], S("Cairn Bout", "Opposed fiction • at-risk wrestler makes STR or DEX save", "Win a save to claim 1 Hold; at 2 Hold, score the fall.", "Failure resets your Hold. A natural 20 also deals d4 STR; stop the bout if Critical Damage occurs.")),
      E("crooked-crowns", "Crooked Crowns Court", "Precision game", 50, 75, "Players cast six wooden crowns toward three leaning posts. A crown scores only if it hangs without touching the ground.", ["Near post: 1 point; middle: 2; far: 3.", "Each player casts six crowns.", "A hanging crown may be knocked free by a later throw."], S("Cairn Contest", "Six throws • DEX save for each", "Success scores 1; success by 5+ scores 2; natural 1 scores 3.", "A player may risk the far post: failure scores 0, success scores 3.")),
      E("gear-pavilion", "Gamekeepers’ Pavilion", "Equipment house", 55, 24, "A striped shelter stores balls, girdles, crowns, chalk, splints, and water.", ["Game set: 10 gp.", "Bandages (3 uses): 30 gp."], S("Toma Reed, Gamekeeper", "5 HP, 12 STR, 12 DEX, 14 WIL, whistle (d4)", "Stops play immediately for injury.", "Can judge a disputed line from almost anywhere on the green.")),
      E("commons", "The Common Turf", "Public space", 50, 50, "Picnics, drills, assemblies, and children’s games fill the field between marked courts.", ["A few minutes with water restores HP.", "Large gatherings act as a detachment if panic begins."], S("Festival Crowd", "8 HP, 10 STR, 9 DEX, 11 WIL, rush (d8 blast), detachment", "Usually curious or kind.", "Critical Damage: the crowd scatters into adjacent lanes.")),
    ],
  },
  {
    id: "market",
    marker: 5,
    name: "Root Market",
    short: "Trade beneath the exposed roots",
    subtitle: "Food, tools, charms, remedies, and public bargains",
    icon: "⌑",
    x: 61,
    y: 68,
    image: "/maps/root-market.webp",
    alt: "Charcoal map of the Root Market and its stalls",
    description:
      "Canvas roofs fill the market court beneath exposed roots. Prices are chalked in gold pieces. Haggling is expected once, courtesy is expected always, and the public well belongs to no stall.",
    facts: ["Market bell: dawn to late afternoon.", "All listed prices use Cairn 2e gold-piece scale.", "A red cord marks medicine; a white cord marks prepared food."],
    entries: [
      E("root-bulb", "Root & Bulb", "Produce stall", 27, 23, "Hanging onions, cave carrots, bitterroot, and bundles of cooking herbs.", ["Keeper: Nessa Coil, who weighs produce with polished river stones.", "She accepts clean seed in trade."], S("Nessa Coil", "3 HP, 10 STR, 11 DEX, 13 WIL, pruning knife (d6)", "Identifies common edible roots without a save.", "Protects her seed chest before her coin."), [["Root vegetables, 3 uses", "5 gp"], ["Travel rations, 3 uses", "10 gp"], ["Fresh herb bundle", "2 gp"]]),
      E("black-sap", "Black-Sap Remedies", "Apothecary stall", 26, 40, "Dark bottles, waxed bandages, bitter tonics, and clearly written warning tags.", ["Keeper: Chirurgeon Vey, licensed and severe.", "A free sniff test catches spoiled medicine."], S("Chirurgeon Vey", "4 HP, 9 STR, 12 DEX, 15 WIL, lancet (d4)", "Can restore Attribute loss with a week’s care.", "Will not promise a cure that the stall cannot provide."), [["Antitoxin", "20 gp"], ["Bandages, 3 uses", "30 gp"], ["Sedative", "30 gp"], ["Medical healing", "50 gp"]]),
      E("mushroom-wife", "Mushroom Wife", "Fungal stall", 26, 57, "Cultivated caps arranged by flavor, not color. Tiny chalk moons mark varieties safe to eat raw.", ["Keeper: Goodwife Pell, addressed by the stall’s old title.", "Unknown wild fungi are inspected for 1 gp."], S("Goodwife Pell", "3 HP, 8 STR, 10 DEX, 14 WIL, sickle (d6)", "Never mistakes a local edible fungus.", "Critical Damage: her spore pouch bursts; nearby creatures save STR or cough helplessly for one round."), [["Meal-cap, 3 uses", "6 gp"], ["Glowcap, 3 uses of dim light", "8 gp"], ["Spore repellent", "10 gp"]]),
      E("bone-button", "Bone & Button", "Haberdashery", 26, 72, "Needles, toggles, carved clasps, combs, and small repairs while you wait.", ["Keeper: Orrit Bonehand.", "Custom buttons may carry a simple public emblem."], S("Orrit Bonehand", "3 HP, 9 STR, 13 DEX, 11 WIL, shears (d6)", "Repairs cloth gear in one turn.", "Can duplicate an ordinary button or buckle by touch."), [["Sewing kit", "20 gp"], ["Clothing repair", "5 gp"], ["Carved button set", "3 gp"]]),
      E("tinker", "Tinker’s Booth", "Repair stall", 32, 88, "Pots, lenses, locks, lamp hinges, and a constant tapping under a patched awning.", ["Keeper: Jori Tapp.", "Repairs are guaranteed until the next dawn."], S("Jori Tapp", "4 HP, 10 STR, 14 DEX, 12 WIL, hammer (d6)", "Common repairs take one turn; complex repairs take a day.", "A failed repair attempt by anyone else raises Jori’s price by 5 gp."), [["Common tools", "10 gp"], ["Specialized tools", "20 gp"], ["Lantern repair", "5 gp"]]),
      E("ironmonger", "Ironmonger", "Weapons and hardware", 56, 24, "Hooks, nails, blades, helmets, chain, and tools hang in disciplined rows.", ["Keeper: Harn Blackthumb.", "Weapons are peace-bound before leaving the stall."], S("Harn Blackthumb", "6 HP, 1 Armor, 15 STR, 9 DEX, 12 WIL, forge hammer (d8)", "Judges cracked metal at a glance.", "Critical Damage: knocks the target prone and disarms them."), [["Dagger or cudgel, d6", "5 gp"], ["Sword, spear, or axe, d8", "10 gp"], ["Chain, 10 ft", "10 gp"], ["Helmet, +1 Armor", "10 gp"]]),
      E("charm-peddler", "Charm Peddler", "Curio stall", 57, 42, "Knotted cords, bell-thorns, painted stones, and little promises sold with exact wording.", ["Keeper: Senn-of-Seven-Knots.", "Every charm states whether its effect is custom, faith, or craft."], S("Senn-of-Seven-Knots", "3 HP, 8 STR, 12 DEX, 15 WIL, thorn pin (d4)", "Can tie a one-use charm that grants +1 Armor against a named hazard.", "The charm occupies one slot and unravels after use."), [["Traveler’s knot", "10 gp"], ["Quiet bell", "15 gp"], ["Repellent charm", "10 gp"]]),
      E("cage-bread", "Cage Bread", "Bakery stall", 59, 58, "Dense ring-loaves sized to pass through cage bars. Warm steam carries caraway and salt.", ["Keeper: Auntie Morra.", "One loaf feeds a person for a day."], S("Auntie Morra", "4 HP, 12 STR, 9 DEX, 13 WIL, bread paddle (d6)", "Gives water freely.", "Will wrap paid bread for a named prisoner at no extra charge."), [["Ring-loaf", "1 gp"], ["Rations, 3 uses", "10 gp"], ["Sweet ash bun", "2 gp"]]),
      E("frost-fish", "Frost Fish", "Fishmonger", 60, 73, "Pale river fish lie on blue root-ice that never quite melts.", ["Keeper: Kel and his silent cormorant.", "The bird points at the freshest catch."], S("Kel Frostnet", "4 HP, 11 STR, 12 DEX, 10 WIL, fillet knife (d6)", "Casts a weighted net (DEX save or entangled).", "Cuts anyone free before continuing a quarrel."), [["Fresh fish, 3 uses", "5 gp"], ["Fishing rod", "10 gp"], ["Weighted net", "10 gp"]]),
      E("old-root-tea", "Old Root Tea", "Tea stall", 58, 88, "A long counter of clay cups and labeled roots. Conversation is welcome; shouting is not.", ["Keeper: Grandmother Sile.", "Ten quiet minutes and water restore HP."], S("Grandmother Sile", "3 HP, 7 STR, 9 DEX, 16 WIL, walking stick (d6)", "A listener who never repeats a confidence in public.", "Her bitter tea lets a deprived traveler ignore deprivation for one hour, once per day."), [["Clay cup", "1 gp"], ["Restorative pot for four", "5 gp"], ["Dried tea, 3 uses", "5 gp"]]),
      E("well", "Public Well", "Civic utility", 43, 55, "A stone well with two buckets, a trough, and a brass plaque forbidding private ownership.", ["Water is free.", "A few moments drinking in safety restores HP."], S("Root Well", "Site • STR save when hauling a person or bulky load", "Failure: lose grip and take d4 STR from the crank.", "The water is clean, cold, and ordinary.")),
      E("butcher-1", "Butcher Row 1 — Red Hook", "Meat stall", 80, 38, "Fresh cuts, smoked links, and a spotless red-painted hook.", ["Keeper: Brann Red Hook.", "Posts the animal and slaughter date."], S("Brann", "5 HP, 13 STR, 10 DEX, 11 WIL, cleaver (d8)", "Keeps every blade visibly sharp.", "Critical Damage: severs a strap, belt, or carried item before flesh."), [["Fresh meat, 3 uses", "8 gp"], ["Smoked links, 3 uses", "10 gp"]]),
      E("butcher-2", "Butcher Row 2 — Marrow Pot", "Cook stall", 80, 52, "Broth, marrow toast, and onions served at a standing table.", ["Keeper: Della Pot.", "One bowl counts as a hot meal."], S("Della Pot", "4 HP, 12 STR, 9 DEX, 14 WIL, iron ladle (d6)", "Feeds an injured person before collecting payment.", "A full bowl and a turn of rest clears 1 Fatigue once per week."), [["Broth bowl", "2 gp"], ["Marrow ration, 3 uses", "10 gp"]]),
      E("butcher-3", "Butcher Row 3 — Hide & Suet", "Materials stall", 80, 66, "Cured hide, wax, glue, sinew, and wrapped suet bricks.", ["Keeper: Pell Marran.", "Buys clean hides at half posted value."], S("Pell Marran", "4 HP, 11 STR, 11 DEX, 12 WIL, hide scraper (d6)", "Can patch leather armor in one turn.", "A repaired item is sound but visibly scarred."), [["Common agents", "10 gp"], ["Hide repair", "5 gp"], ["Firestarter suet, 3 uses", "5 gp"]]),
      E("butcher-4", "Butcher Row 4 — White Cleaver", "Prepared food stall", 80, 81, "Cold pies and preserved meat stamped with a white cleaver.", ["Keeper: Twins Maud and Mern.", "Their pies keep for a week."], S("Maud & Mern", "5 HP, 11 STR, 13 DEX, 12 WIL, cleavers (d6+d6)", "Act together and finish each other’s prices.", "If one is hurt, the other’s attacks are enhanced until they can withdraw."), [["Travel pie", "3 gp"], ["Rations, 3 uses", "10 gp"]]),
      E("north-rootway", "North Rootway", "Market entrance", 42, 24, "A root-arched path toward the Tree and upper wards. Porters wait beside handcarts.", ["Porter: 5 gp per day.", "Handcart: 30 gp."], S("Market Porters", "6 HP, 12 STR, 10 DEX, 10 WIL, poles (d6), detachment", "Helpful when treated as workers rather than furniture.", "Morale check when cargo, not coin, is threatened.")),
      E("south-gate-road", "South Gate Road", "Market entrance", 44, 96, "The paved lane to Root Gate, cart scales, and the farms beyond the wall.", ["Road tolls are posted at the gate, not collected here.", "Carts keep right; pedestrians use the root-side curb."], S("Cart Traffic", "Hazard • DEX save • collision: d6 STR", "A bell or shouted warning removes surprise.", "At night the road is empty but poorly lit.")),
    ],
  },
  {
    id: "shrine",
    marker: 6,
    name: "Old Shrine",
    short: "Prayer above, catacombs below",
    subtitle: "A public ruin, maintained chapels, and marked lower chambers",
    icon: "♜",
    x: 81,
    y: 32,
    image: "/maps/old-shrine.webp",
    alt: "Charcoal floor plan of the Old Shrine",
    portrait: true,
    description:
      "The Old Shrine remains open by daylight. Its upper rooms house a small serving order; the nave receives pilgrims; the mapped catacombs are entered only with lamps and a signed descent token.",
    facts: ["Quiet speech is customary, not compulsory.", "Offerings support food, lamps, and repairs.", "The lower plan is public because search parties depend on it."],
    entries: [
      E("monk-cells", "Monk Cells", "Second floor", 23, 13, "Narrow rooms with cots, washbowls, pegs, and small writing shelves.", ["A traveler may request one night’s simple shelter.", "Room and board: 10 gp when space allows."], S("Shrine Attendant", "3 HP, 9 STR, 10 DEX, 13 WIL, staff (d6)", "Offers hospitality before doctrine.", "Will wake the floor by striking the doorframe three times.")),
      E("refectory", "Refectory", "Second floor", 56, 13, "A single long table beneath smoke-dark rafters.", ["Common meal at dusk: 3 gp or one hour of work.", "A meal and safe rest restore HP."], S("Common Table", "Sanctuary • no save", "Drawing a weapon ends sanctuary immediately.", "The serving order refuses no one water.")),
      E("kitchen", "Kitchen", "Second floor", 81, 13, "Stone hearth, hanging pots, root-cellar hatch, and a constant scent of broth.", ["Cooking gear: not for sale.", "Helping for a turn earns a meal."], S("Hearth Flare", "Hazard • DEX save • d6 STR", "A wet cloth or sand smothers it.", "Oil makes the damage blast on a failed Die of Fate.")),
      E("spiral-stairs", "Spiral Stairs 1 & 2", "Vertical routes", 15, 41, "Matched stone spirals connect the three mapped levels. Brass numerals at every landing prevent a hurried traveler from mistaking one for the other.", ["Moving carefully requires no save.", "Rushing, fighting, or carrying bulky gear requires a DEX save."], S("Shrine Spiral", "Hazard • DEX save • fall: d6 STR", "A hand on the central rail avoids the save during ordinary travel.", "A dropped object descends one mapped level on an unfavorable Die of Fate.")),
      E("pantry", "Pantry", "Second floor", 83, 18, "Labeled sacks, jars, dried apples, and cage loaves stacked on slatted shelves.", ["Rations are issued against the public ledger.", "Spoiled food is marked with black twine."], S("Pantry Mice", "2 HP, 4 STR, 14 DEX, 5 WIL, bite (d4)", "Flee light and stamping.", "Critical Damage: the target drops one exposed ration, which is spoiled.")),
      E("washroom", "Washroom", "Second floor", 82, 23, "Cold basins and a copper kettle serve residents and pilgrims.", ["Washing takes one turn.", "Clean bandages used here stabilize without contamination."], S("Slippery Tile", "Hazard • DEX save • fall: d4 STR", "Walking slowly avoids the save.", "A spilled kettle adds d4 burn damage.")),
      E("scriptorium", "Scriptorium", "Second floor", 80, 30, "Desks, public prayer sheets, civic copies, and sharpened quills face the east windows.", ["Copying service: 20 gp per day.", "Parchment (3 uses): 10 gp."], S("Sister Hale, Copyist", "3 HP, 8 STR, 12 DEX, 14 WIL, penknife (d4)", "Reads the common scripts of Marr.", "Never alters a quoted speaker’s words.")),
      E("archive", "Archive", "Second floor", 63, 32, "Locked cabinets hold public registers, repairs, births, and shrine donations.", ["A serving monk retrieves requested public records.", "Rare-book handling requires clean gloves."], S("Archive Cabinet", "8 HP, 2 Armor, 12 STR, 5 DEX, 10 WIL", "Thieving tools can open a lawful stuck lock in one turn.", "Breaking it makes d6 records unusable.")),
      E("abbot-room", "Abbot’s Chamber", "Second floor", 48, 32, "A receiving room with two chairs, a low desk, and no throne.", ["Private counsel is free but scheduled.", "Medical healing may be arranged for 50 gp."], S("Prior Elian", "4 HP, 9 STR, 11 DEX, 16 WIL, staff (d6)", "Communicates clearly by gesture, slate, and patient attention.", "Can calm a willing panicked person after one quiet turn.")),
      E("altar", "Main Altar", "Ground floor", 51, 43, "A plain stone altar beneath a carved tree. Fresh water and names written on bark slips are the common offerings.", ["Offering is voluntary.", "A sincere hour of vigil clears 1 Fatigue once per week."], S("Altar Peace", "Sanctuary • WIL save to commit violence", "Success permits the act but ends all shrine hospitality.", "Failure: the aggressor cannot cross the altar rail this turn.")),
      E("ritual-circle", "Ritual Circle", "Ground floor", 50, 52, "An inlaid ring used for public oaths, mourning songs, and seasonal blessings.", ["Four participants can conduct a witnessed oath.", "False speech inside the ring causes no magical punishment; the witnesses still hear it."], S("Witnessed Oath", "Procedure • WIL save to speak through fear or pressure", "Success preserves exact wording in the shrine register.", "Failure means the speaker must pause and may try again after rest.")),
      E("vestry", "Vestry", "Ground floor", 29, 42, "Robes, candles, washcloths, and ceremony tools are stored behind a half door.", ["Costume gear: 15 gp with a deposit.", "Open flame is never left unattended."], S("Wax Rack", "Hazard • DEX save • falling candles: d4 STR", "The rack is unstable only when climbed.", "Spilled wax makes the floor difficult until scraped.")),
      E("offering-room", "Offering Room", "Ground floor", 70, 42, "Shelves display bread, cloth, tools, coins, and written pledges awaiting distribution.", ["A public slate lists where goods will go.", "Taking from the room requires authorization, not a roll."], S("Offering Steward", "3 HP, 9 STR, 10 DEX, 14 WIL, bell (d4)", "Can issue basic clothing or a meal to a person in need.", "Uses the bell to summon attendants, never as a weapon if escape is possible.")),
      E("chapels", "Side Chapels", "Ground floor", 22, 55, "Two small chapels hold benches, memory candles, and wooden tablets for personal names.", ["One chapel is kept silent; the other permits soft song.", "A candle costs 1 gp."], S("Memory Candle", "Relic • 1 use • WIL save", "On success, remain awake and alert through one night without Fatigue.", "On failure, add 1 Fatigue at dawn as ordinary.")),
      E("incense-room", "Incense Preparation", "Ground floor", 81, 50, "Mortars, drying racks, masks, and sealed clay jars fill the room.", ["Repellent bundle: 10 gp.", "Breathing a dense spill requires a STR save."], S("Incense Cloud", "Hazard • STR save • failure: deprived for one turn", "A wet cloth negates the save.", "Strong wind disperses the cloud immediately.")),
      E("basin", "Purification Basin", "Ground floor", 80, 62, "A round basin catches rainwater from a copper chain.", ["Water is clean enough to drink.", "Washing ash or blood here takes one turn."], S("Basin Water", "Resource • 6 uses per day", "One use restores HP when safe.", "After six uses, only rain refills it.")),
      E("nave", "The Nave", "Ground floor", 50, 49, "Rows of plain benches face the altar with broad aisles between them. Pilgrims, mourners, and village meetings share the same floor.", ["Sitting with water for a few minutes restores HP.", "A packed congregation counts as a detachment if panic begins."], S("Nave Congregation", "7 HP, 10 STR, 9 DEX, 12 WIL, rush (d8 blast), detachment", "Usually curious, solemn, or helpful.", "Critical Damage: the gathering breaks into frightened groups and clears the central aisle.")),
      E("narthex", "Narthex", "Ground floor", 50, 59, "The entry hall holds cloak pegs, lamp niches, a donation box, and the posted plan of the shrine.", ["Wet cloaks and muddy boots are left here.", "A public descent token can be requested at the attendant’s bench."], S("Narthex Attendant", "3 HP, 9 STR, 11 DEX, 13 WIL, lamp pole (d6)", "Explains the map and current closures.", "Carries spare chalk and will mark a visitor’s intended lower route.")),
      E("ossuary", "Ossuary", "Catacombs", 48, 72, "Named bones rest in wall niches around a central stone table. Visitors are asked to keep packs from scraping the plaques.", ["A descent token and lantern are required.", "Moving quickly requires a DEX save."], S("Loose Bone Shelves", "Hazard • DEX save • collapse: d6 STR", "Walking carefully avoids the save.", "Damage also extinguishes one open flame on a failed Die of Fate.")),
      E("flooded-crypt", "Flooded Crypt", "Catacombs", 24, 80, "Cold black water covers the western chamber to waist height. Stone lids break the surface like islands.", ["Movement is halved.", "A STR save is required while carrying bulky gear."], S("Crypt Water", "Hazard • STR save each turn • failure: 1 Fatigue", "A rope line removes the save.", "Dropped metal sinks beyond easy reach.")),
      E("reliquary", "Reliquary", "Catacombs", 74, 73, "An iron-grilled chamber containing sealed boxes and a stone display chest. Its posted inventory lists only public devotional objects.", ["The grille is opened for festival viewings.", "No object may be handled without a shrine attendant."], S("Reliquary Grille", "10 HP, 3 Armor, 16 STR, 4 DEX, 12 WIL", "Mundane hand weapons are impaired against it.", "The visible lock accepts specialized thieving tools.")),
      E("monster-den", "Claw-Marked Den", "Catacombs", 74, 82, "The public plan names this chamber by its old warning: deep scratches, nest litter, and a rank animal odor.", ["Fresh tracks mean the lower route is closed.", "The creature’s identity is not assumed until encountered."], S("Rootmaw", "8 HP, 1 Armor, 15 STR, 12 DEX, 7 WIL, bite (d10)", "A bark-scaled ambush predator that retreats from open flame.", "Critical Damage: drags the target into near cover; STR save to break free.")),
      E("sealed-chamber", "Sealed Chamber", "Catacombs", 48, 87, "An old floor-plan label marks a circular chamber beyond a barred descent. Only its threshold is part of the public route.", ["The barrier is visibly maintained.", "The atlas offers no contents or bypass."], S("Descent Barrier", "12 HP, 3 Armor, 16 STR, 5 DEX, 14 WIL", "Attacks against it are impaired.", "Opening it lawfully requires a current shrine writ.")),
      E("depths-unmapped", "Depths Unmapped", "Catacombs", 50, 96, "The stair continues beyond survey marks and maintained lamps.", ["Public tokens do not authorize entry.", "Unmapped travel uses the Deep-Root Exposure rules."], S("Unmapped Descent", "Journey • WIL save each watch • failure: 1 Fatigue", "No navigation roll can reveal information that is not in this player atlas.", "A safe return point and enough light are required to recover HP.")),
    ],
  },
  {
    id: "watch",
    marker: 7,
    name: "Daemos Watch",
    short: "Law, records, and the northern door",
    subtitle: "A public fortress grown against the roots",
    icon: "♜",
    x: 57,
    y: 47,
    image: "/maps/daemos-watch.webp",
    alt: "Charcoal floor plan of Daemos Watch",
    portrait: true,
    description:
      "The Watch is Marr’s stone fist and civic shield. Its front desk, hearing hall, records counter, and visitor gallery are open by posted hours. Armed interior rooms remain plainly restricted.",
    facts: ["Weapons are peace-bound at entry.", "Public complaints receive a numbered slate.", "Names of officers on duty are posted at the desk."],
    entries: [
      E("watch-steps", "Front Steps & Desk", "Public entrance", 50, 87, "Wide steps lead to two doors and a central desk under the gate arch.", ["Visitors receive a clay number.", "Open flame and drawn weapons are refused."], S("Door Constables", "5 HP, 2 Armor, 12 STR, 11 DEX, 13 WIL, spears (d8)", "Question first; restrain second.", "One uses a whistle to call the hall detachment.")),
      E("visitor-gallery", "Visitor Gallery", "South-east room", 72, 75, "A round table, six chairs, public notices, and water under guard supervision.", ["Meetings are limited to one turn when crowded.", "Messages may be deposited with a named recipient."], S("Gallery Officer", "4 HP, 1 Armor, 10 STR, 12 DEX, 14 WIL, cudgel (d6)", "Reads public notices aloud on request.", "Keeps a clear route to the exit.")),
      E("public-armory", "Peace-Bond Armory", "South-west room", 27, 75, "Racks hold checked weapons behind a counter. Each item receives a matching lead token.", ["Checking a weapon is free.", "Lost token: identity and witness required."], S("Armory Keeper", "5 HP, 2 Armor, 13 STR, 10 DEX, 12 WIL, mace (d8)", "Returns only the item matching the token.", "Can lock all racks with one lever.")),
      E("central-hall", "Central Hall", "Processional chamber", 50, 52, "Stone pillars divide the long hall. A compass rose marks the floor; benches line the walls.", ["Crossing takes moments unless a queue blocks the way.", "Running through a crowd requires a DEX save."], S("Watch Hall Detail", "8 HP, 2 Armor, 13 STR, 11 DEX, 13 WIL, polearms (d10), detachment", "Maintains lanes and protects bystanders.", "Morale uses the hall captain’s 14 WIL.")),
      E("hearing-hall", "Hearing Hall", "North rotunda", 50, 26, "A raised central table faces public benches. Statements are spoken, repeated by a clerk, then entered in the day ledger.", ["Any named party may request the written wording.", "WIL save to testify under immediate threat."], S("Magistrate Orra Vale", "4 HP, 10 STR, 10 DEX, 16 WIL, gavel (d4)", "Insists on exact claims and named witnesses.", "Can suspend a hearing rather than let violence decide it.")),
      E("north-root-door", "North Root Door", "Restricted gate", 50, 10, "An iron door opens into a root passage beyond the public floor. A painted sign lists closures and authorized duties.", ["No visitor access without an escort.", "The door’s status is visible: open, guarded, or sealed."], S("Root Door", "14 HP, 3 Armor, 18 STR, 3 DEX, 14 WIL", "Mundane attacks are impaired.", "A legal seal and two officers are required to open it.")),
      E("west-barracks", "West Barracks", "Restricted room", 25, 38, "Rows of bunks, footlockers, washstands, and duty boards are visible when the doors stand open.", ["Not a public sleeping house.", "A duty sergeant may recruit bodyguards for 10 gp per day."], S("Off-duty Watch", "6 HP, 1 Armor, 12 STR, 11 DEX, 12 WIL, swords (d8), detachment", "Unarmored unless alarmed.", "Takes one round to form a detachment.")),
      E("west-stores", "West Stores", "Restricted room", 24, 56, "Barrels, shields, rope, lamps, and sealed evidence crates are stacked by painted category.", ["Public lost property is released at the front desk.", "No shop operates here."], S("Toppling Stores", "Hazard • DEX save • d8 STR", "Triggered only by climbing or violent impact.", "A careful search takes one turn per bay.")),
      E("east-records", "Records Office", "Public counter", 75, 41, "Clerks work behind a long table among shelves of current notices and case copies.", ["Public copy: 5 gp.", "A scholar may be hired for 20 gp per day."], S("Records Clerk Detachment", "5 HP, 8 STR, 10 DEX, 14 WIL, ink pots (d4 blast), detachment", "Defends records by closing shutters.", "Will preserve people before paper if fire starts.")),
      E("east-briefing", "Briefing Room", "Restricted room", 75, 57, "A large table bears removable public map tiles and duty rosters.", ["Current road closures are copied to the entrance board.", "Visitors may attend announced safety briefings."], S("Watch Captain Sera Venn", "7 HP, 2 Armor, 14 STR, 12 DEX, 15 WIL, longsword (d10, bulky)", "Protects an evacuation route before pursuing a foe.", "Critical Damage: orders the target disarmed and stabilized.")),
      E("spiral-towers", "Spiral Towers", "Stairwells", 82, 76, "Four round stairs connect the watch floor to parapets and root-level service ways.", ["Visitors use only the south-east stair.", "Descending during alarm requires a DEX save."], S("Crowded Spiral", "Hazard • DEX save • fall: d6 STR", "Moving at half pace avoids the save.", "A shield or bulky pack makes the save impaired.")),
    ],
  },
  {
    id: "gate",
    marker: 8,
    name: "Root Gate",
    short: "Marr’s southern threshold",
    subtitle: "Road, toll, wall, and first welcome",
    icon: "♜",
    x: 53,
    y: 87,
    image: "/maps/root-gate.webp",
    alt: "Focused charcoal map of Root Gate",
    description:
      "Twin towers flank the southern road where the wall bends around a massive buried root. Traders queue at the scales; pedestrians pass beneath the smaller arch.",
    facts: ["Gate hours: dawn to evening bell.", "Emergency night entry requires a name and reason.", "Posted tolls are paid only once per arrival."],
    entries: [
      E("road-arch", "Road Arch", "Main gate", 50, 42, "A portcullis, timber doors, murder-slot canopy, and broad wagon lane.", ["Carts move one at a time.", "The bell sounds before either barrier moves."], S("Root Gate Detail", "8 HP, 2 Armor, 13 STR, 11 DEX, 13 WIL, crossbows (d8, bulky), detachment", "Warns before closing the lane.", "Enhanced attacks against anyone trapped beneath the portcullis.")),
      E("foot-arch", "Traveler’s Arch", "Pedestrian gate", 73, 48, "A smaller side passage with benches, a water barrel, and inspection table.", ["No toll for a person on foot.", "Bulky goods are directed to the scales."], S("Gate Examiner", "4 HP, 1 Armor, 10 STR, 12 DEX, 14 WIL, cudgel (d6)", "Explains every public rule when asked.", "Confiscates only items named on the posted list.")),
      E("cart-scales", "Cart Scales", "Trade station", 27, 67, "A timber platform weighs carts and cargo before market entry.", ["Cart: 30 gp; wagon: 200 gp in Cairn marketplace scale.", "Toll varies by cargo and is chalked daily."], S("Scale Platform", "Device • STR save to shift overloaded cargo", "Failure: d4 STR from strain or add 1 Fatigue.", "Using a mule or pulley removes the save.")),
      E("gatehouse", "Gatehouse", "Civic office", 30, 44, "Toll slates, road notices, missing-person sheets, and travel permits fill a public vestibule.", ["Local guide: 5 gp per day.", "Parchment travel copy: 5 gp."], S("Gate Scribe", "3 HP, 8 STR, 11 DEX, 14 WIL, penknife (d4)", "Knows public roads, closures, and posted hazards.", "Will not invent certainty when a road report is old.")),
      E("outer-road", "Old Processional Road", "Surface road", 52, 84, "The stone road runs south between fields before fading into older country.", ["A walking watch covers about six miles.", "Travel after dark requires a lantern or WIL save to keep direction."], S("Road Exposure", "Journey • WIL save each dark watch • failure: 1 Fatigue", "A local guide removes the first save.", "Bad weather may call for a STR save instead.")),
    ],
  },
];

const MARR_OVERVIEW_STAT = S(
  "Marr, Walled Root-Village",
  "Settlement • watch detachment: 8 HP, 2 Armor, 13 STR, 11 DEX, 13 WIL, polearms (d10)",
  "Water, common food, rooms, repairs, guides, and ordinary weapons are available.",
  "A few minutes of safe rest with water restores HP.",
  "Public law is posted at Root Gate, the Tree petition hall, and Daemos Watch."
);

window.MARR_ATLAS = { destinations: MARR_DESTINATIONS, overviewStat: MARR_OVERVIEW_STAT };
})();
